from System import IDisposable

class BufferManagerContext:
    def IsNeedBlocking(self) -> bool: ...
    def SetNeedBlocking(self, needsBlocking: bool) -> None: ...


class ScopedBufferManagerContextRegistration(IDisposable):
    def __init__(self, unused: int = ...) -> None: ...
    def Dispose(self) -> None: ...

