from System.IO import Stream
from System import Array_1

class Calibration:
    def __init__(self, stream: Stream) -> None: ...
    AccelerometerOffset : Array_1[int]
    AccelerometerScale : Array_1[int]
    AmiiboCertEcdsa : Array_1[int]
    AmiiboCertEcqv : Array_1[int]
    AmiiboCertEcqvBls : Array_1[int]
    AmiiboKey : Array_1[int]
    AmiiboKeyEcqvBls : Array_1[int]
    AmiiboRootCertEcqvBls : Array_1[int]
    AnalogStickFactoryCalibrationL : Array_1[int]
    AnalogStickFactoryCalibrationR : Array_1[int]
    AnalogStickModelParameterL : Array_1[int]
    AnalogStickModelParameterR : Array_1[int]
    AnalogStickModuleTypeL : Array_1[int]
    AnalogStickModuleTypeR : Array_1[int]
    BatteryLot : str
    BatteryVersion : Array_1[int]
    BdAddr : Array_1[int]
    CalibDataSha256 : Array_1[int]
    CalibDataSize : int
    ColorVariation : Array_1[int]
    ConfigId1 : str
    ConsoleSixAxisSensorHorizontalOffset : Array_1[int]
    ConsoleSixAxisSensorModuleType : Array_1[int]
    ConsoleSixAxisSensorMountType : Array_1[int]
    DeviceCertEccB233 : Array_1[int]
    DeviceCertEccP256 : Array_1[int]
    DeviceExtKeyEccB233 : Array_1[int]
    DeviceKeyEccB233 : Array_1[int]
    DeviceKeyEccP256 : Array_1[int]
    EticketCertEccB233 : Array_1[int]
    EticketCertEccP256 : Array_1[int]
    EticketCertRsa : Array_1[int]
    EticketExtKeyEccB233 : Array_1[int]
    EticketExtKeyEccP256 : Array_1[int]
    EticketExtKeyRsa : Array_1[int]
    EticketKeyEccB233 : Array_1[int]
    EticketKeyEccP256 : Array_1[int]
    EticketKeyRsa : Array_1[int]
    ExpectedMagic : str
    ExtendedRsa2048DeviceKey : Array_1[int]
    GamecardCert : Array_1[int]
    GamecardCertSha256 : Array_1[int]
    GamecardExtKey : Array_1[int]
    GamecardKey : Array_1[int]
    GyroscopeOffset : Array_1[int]
    GyroscopeScale : Array_1[int]
    HomeMenuSchemeBezelColor : int
    HomeMenuSchemeMainColor1 : int
    HomeMenuSchemeMainColor2 : int
    HomeMenuSchemeMainColor3 : int
    HomeMenuSchemeModel : int
    HomeMenuSchemeSubColor : int
    LcdBacklightBrightnessMapping : Array_1[int]
    LcdVendorId : int
    Magic : str
    Model : int
    ProductModel : int
    RandomNumber : Array_1[int]
    RandomNumberSha256 : Array_1[int]
    RegionCode : int
    Reserved : Array_1[int]
    Revision : int
    Rsa2048DeviceCertificate : Array_1[int]
    SerialNumber : str
    SpeakerCalibValue : Array_1[int]
    SslCert : Array_1[int]
    SslCertSha256 : Array_1[int]
    SslCertSize : int
    SslExtKey : Array_1[int]
    SslKey : Array_1[int]
    UsbTypeCPowerSourceCircuitVersion : Array_1[int]
    Version : int
    WlanCountryCodes : Array_1[str]
    WlanCountryCodesLastIdx : int
    WlanCountryCodesNum : int
    WlanMacAddr : Array_1[int]

