import typing
from System.IO import Stream, BinaryReader
from System import Array_1
from LibHac.Ncm import ContentMetaAttribute, ContentMetaType, ContentType, UpdateType
from LibHac.Tools.FsSystem.NcaUtils import TitleVersion

class Cnmt:
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, file: Stream) -> None: ...
    @property
    def ApplicationTitleId(self) -> int: ...
    @property
    def ContentEntries(self) -> Array_1[CnmtContentEntry]: ...
    @property
    def ContentEntryCount(self) -> int: ...
    @property
    def ContentMetaAttributes(self) -> ContentMetaAttribute: ...
    @property
    def ExtendedData(self) -> CnmtExtended: ...
    @property
    def FieldD(self) -> int: ...
    @property
    def Hash(self) -> Array_1[int]: ...
    @property
    def MetaEntries(self) -> Array_1[CnmtContentMetaEntry]: ...
    @property
    def MetaEntryCount(self) -> int: ...
    @property
    def MinimumApplicationVersion(self) -> TitleVersion: ...
    @property
    def MinimumSystemVersion(self) -> TitleVersion: ...
    @property
    def PatchTitleId(self) -> int: ...
    @property
    def TableOffset(self) -> int: ...
    @property
    def TitleId(self) -> int: ...
    @property
    def TitleVersion(self) -> TitleVersion: ...
    @property
    def Type(self) -> ContentMetaType: ...


class CnmtContentEntry:
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, reader: BinaryReader) -> None: ...
    @property
    def Hash(self) -> Array_1[int]: ...
    @Hash.setter
    def Hash(self, value: Array_1[int]) -> Array_1[int]: ...
    @property
    def NcaId(self) -> Array_1[int]: ...
    @NcaId.setter
    def NcaId(self, value: Array_1[int]) -> Array_1[int]: ...
    @property
    def Size(self) -> int: ...
    @Size.setter
    def Size(self, value: int) -> int: ...
    @property
    def Type(self) -> ContentType: ...
    @Type.setter
    def Type(self, value: ContentType) -> ContentType: ...


class CnmtContentMetaEntry:
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, reader: BinaryReader) -> None: ...
    @property
    def TitleId(self) -> int: ...
    @property
    def Type(self) -> ContentType: ...
    @property
    def Version(self) -> TitleVersion: ...


class CnmtDeltaSetInfo:
    def __init__(self, reader: BinaryReader) -> None: ...
    @property
    def DeltaContentCount(self) -> int: ...
    @property
    def FragmentSetCount(self) -> int: ...
    @property
    def TitleIdNew(self) -> int: ...
    @property
    def TitleIdOld(self) -> int: ...
    @property
    def VersionNew(self) -> TitleVersion: ...
    @property
    def VersionOld(self) -> TitleVersion: ...


class CnmtExtended:
    def __init__(self, reader: BinaryReader) -> None: ...
    @property
    def DeltaContentCount(self) -> int: ...
    @property
    def DeltaContents(self) -> Array_1[CnmtContentEntry]: ...
    @property
    def DeltaSetCount(self) -> int: ...
    @property
    def DeltaSets(self) -> Array_1[CnmtDeltaSetInfo]: ...
    @property
    def FragmentMap(self) -> Array_1[FragmentMapEntry]: ...
    @property
    def FragmentSetCount(self) -> int: ...
    @property
    def FragmentSets(self) -> Array_1[CnmtFragmentSetInfo]: ...
    @property
    def PrevContentCount(self) -> int: ...
    @property
    def PrevContents(self) -> Array_1[CnmtPrevContent]: ...
    @property
    def PrevDeltaSetCount(self) -> int: ...
    @property
    def PrevDeltaSets(self) -> Array_1[CnmtPrevDelta]: ...
    @property
    def PrevMetaCount(self) -> int: ...
    @property
    def PrevMetas(self) -> Array_1[CnmtPrevMetaEntry]: ...


class CnmtFragmentSetInfo:
    def __init__(self, reader: BinaryReader) -> None: ...
    @property
    def DeltaType(self) -> UpdateType: ...
    @property
    def FragmentCount(self) -> int: ...
    @property
    def FragmentSetInfoField30(self) -> int: ...
    @property
    def NcaIdNew(self) -> Array_1[int]: ...
    @property
    def NcaIdOld(self) -> Array_1[int]: ...
    @property
    def SizeNew(self) -> int: ...
    @property
    def SizeOld(self) -> int: ...
    @property
    def Type(self) -> ContentType: ...


class CnmtPrevContent:
    def __init__(self, reader: BinaryReader) -> None: ...
    @property
    def NcaId(self) -> Array_1[int]: ...
    @property
    def Size(self) -> int: ...
    @property
    def Type(self) -> ContentType: ...


class CnmtPrevDelta:
    def __init__(self, reader: BinaryReader) -> None: ...
    @property
    def CnmtPrevDeltaField20(self) -> int: ...
    @property
    def Size(self) -> int: ...
    @property
    def TitleIdNew(self) -> int: ...
    @property
    def TitleIdOld(self) -> int: ...
    @property
    def VersionNew(self) -> TitleVersion: ...
    @property
    def VersionOld(self) -> TitleVersion: ...


class CnmtPrevMetaEntry:
    def __init__(self, reader: BinaryReader) -> None: ...
    @property
    def CnmtPrevMetaEntryField32(self) -> int: ...
    @property
    def CnmtPrevMetaEntryField34(self) -> int: ...
    @property
    def ContentCount(self) -> int: ...
    @property
    def Hash(self) -> Array_1[int]: ...
    @property
    def TitleId(self) -> int: ...
    @property
    def Type(self) -> ContentMetaType: ...
    @property
    def Version(self) -> TitleVersion: ...


class FragmentMapEntry:
    def __init__(self, reader: BinaryReader) -> None: ...
    @property
    def ContentIndex(self) -> int: ...
    @property
    def FragmentIndex(self) -> int: ...

